language: node_js
node_js: stable
dist: trusty
addons:
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - master

before_script:
  - set SAUCE_ACCESS_KEY = ${SAUCE_ACCESS_KEY}
  - set SAUCE_USERNAME = ${SAUCE_USERNAME}
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - bower install
  - npm update
  - bower update

script:
  - gulp clean verify build
  - gulp saucelabs

after_success:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'