language: node_js
node_js:
    - "0.10"
dist: trusty
addons:
  sonarqube:
      token:
        secure: ${SONAR_TOKEN}
      branches:
        - DP-312_CreateSonarReportsForDolphinPlatformJs
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  - bower install
  - npm update
  - bower update

script:
  - gulp clean verify build
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'