export const DOLPHIN_PLATFORM_PREFIX = 'dolphin_platform_intern_';
export const CREATE_CONTEXT_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'initClientContext';
export const DESTROY_CONTEXT_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'disconnectClientContext';
export const CREATE_CONTROLLER_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'registerController';
export const DESTROY_CONTROLLER_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'destroyController';
export const CALL_CONTROLLER_ACTION_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'callControllerAction';
export const START_LONG_POLL_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'longPoll';
export const INTERRUPT_LONG_POLL_COMMAND_NAME = DOLPHIN_PLATFORM_PREFIX + 'release';
